# Generated by Django 4.2.3 on 2023-07-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
